IS413_BookStore/Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using IS413_BookStore.Models;
using IS413_BookStore.Infrastructure;

namespace IS413_BookStore.Pages
{
    public class PurchaseModel : PageModel
    {
        private IBookRepository repository;

        public PurchaseModel (IBookRepository repo) // Constructor
        {
            repository = repo;
        }

        // Properties
        public Cart Cart { get; set; }

        public string ReturnUrl { get; set; }

        // GET requests
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        // POST request
        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.BookId == bookId);

            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();

            Cart.AddItem(book, 1);

            HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl });

        }

        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            

            Cart.RemoveLine(Cart.Lines.First(b =>
                b.Book.BookId == bookId).Book);

            HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostClear(string returnUrl)
        {
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();


            Cart.Clear();

            HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

IS413_BookStore/Pages/Purchase.cshtml
@page
@model IS413_BookStore.Pages.PurchaseModel
@{
    ViewData["Title"] = "Cart";
    ViewData["Heading"] = "Shopping Cart";
}
<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Subtotal</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="">@line.Book.Title</td>
                <td class="">@line.Book.AuthorLastName, @line.Book.AuthorFirstName</td>
                <td class="">$@line.Book.Price</td>
                <td class="">@line.Quantity</td>
                <td class="text-right">@((line.Quantity * line.Book.Price).ToString("c", System.Globalization.CultureInfo.GetCultureInfo("en-us")))</td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="bookId"
                                value="@line.Book.BookId" />
                        <input type="hidden" name="returnUrl"
                                value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            <img src="img/trash.svg" />
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="4" class="text-right">Total:</td>
            <td class="text-right">@Model.Cart.ComputeTotalSum().ToString("c", System.Globalization.CultureInfo.GetCultureInfo("en-us"))</td>
        </tr>
    </tfoot>

</table>

<div class="m-auto">
    <a class="btn btn-info mt-4" href="@Model.ReturnUrl">Continue Shopping</a>
</div>
<br />

<div class="m-auto">
    @*<a class="btn text-secondary" href="">Empty Cart</a>*@

    <form asp-page-handler="Clear" method="post">
        <input type="hidden" name="returnUrl"
               value="@Model.ReturnUrl" />
        <button type="submit" class="btn text-secondary">
            Empty Cart
        </button>
    </form>
</div>